[package]
name = "ckb-read-PeerId"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
secio = { version="0.5.7", package="tentacle-secio" }
log = "0.4.17"
simple_logger = "2.3.0"
